version: "2"
#volumes:
#  data-db:

services:

  docker-mysql:
    container_name: docker-mysql
    image: mysql:5.7.12
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=usersmicrodb
     - MYSQL_USER=root
#    volumes:
#      - data-db:/var/lib/mysql
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  config:
    container_name: config
    build:
      context: .
      dockerfile: ./config-service/Dockerfile
    image: config-service
    restart: always
##    logging:
##      options:
##        max-size:
##          - 10m
##        max-file:
##          - 10
    ports:
      - 9002:9002

  eureka-server:
    container_name: eureka-server
    build:
        context: .
        dockerfile: ./eureka-service/Dockerfile
    image: eureka-service
    restart: always
#    logging:
#       options:
#         max-size:
#          "10m"
#         max-file:
#          "10"
    depends_on:
      - config
    entrypoint: /bin/sh
    command: >
            -c "
            while ! $$(sudo docker inspect -f {{.State.Running}} config);
             do sleep 20; echo 'Waiting for config-server services to start-up...'
            java -jar /app/eureka-service.jar;
            done;
            "
    ports:
        - 9001:9001

  gateway:
    build:
        context: .
        dockerfile: ./gateway/Dockerfile
    image: gateway
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - config
      - eureka-server
    entrypoint: /bin/sh
    command: >
            -c "
            while ! $$(sudo docker inspect -f {{.State.Running}} eureka-server);
             do sleep 10; echo 'Waiting for eureka-server services to start-up...'
            java -jar /app/gateway.jar;
            done;
            "

  user-service:
    container_name: user-service
    build:
        context: .
        dockerfile: ./user-service/Dockerfile
    image: user-service
    restart: always
    depends_on:
      - config
      - eureka-server
      - docker-mysql
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=usersmicrodb
      - DATABASE_PORT=3306
    entrypoint: /bin/sh
    command: >
            -c "
            while ! ($$(sudo docker inspect -f {{.State.Running}} eureka-server)&&
            $$(sudo docker inspect -f {{.State.Running}} docker-mysql));
             do sleep 10; echo 'Waiting for eureka-server, docker-mysql services to start-up...'
            java -jar /app/user-service.jar;
            done;
            "
#
  userdashboard-service:
    build:
        context: .
        dockerfile: ./users-dashboard-service/Dockerfile
    image: userdashboard-service
    restart: always
    depends_on:
      - eureka-server
      - user-service
    entrypoint: /bin/sh
    command: >
            -c "
            while ! $$(sudo docker inspect -f {{.State.Running}} user-service);
             do sleep 20; echo 'Waiting for user-service services to start-up...'
            java -jar /app/usersdashboard.jar;
            done;
            "
  currency-service:
    build:
        context: .
        dockerfile: ./currency-service/Dockerfile
    image: currency-service
    restart: always
    depends_on:
      - config
      - eureka-server
    entrypoint: /bin/sh
    command: >
            -c "
            while ! $$(sudo docker inspect -f {{.State.Running}} eureka-server);
             do sleep 20; echo 'Waiting for eureka-server services to start-up...'
            java -jar /app/currency-service.jar;
            done;
            "