server.port: 1111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
  instance:
    preferIpAddress: true

spring:
  datasource:
    url:   jdbc:mysql://localhost:3306/usersmicrodb?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=true&requireSSL=true
    username: root
    password: AA01002aa!
    initialization-mode: always
    data: classpath:/db/users.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
